#ifndef COMPONENT_ID_H
#define COMPONENT_ID_H

#define COMP_NONE 0
#define COMP_ORI 1
#define COMP_VERTICES 2
#define COMP_INDICES 3
#define COMP_TEXTURE 4
#define COMP_GRAVITY 5
#define COMP_VELOCITY 6

#endif//COMPONENT_ID_H